version: '3'
services:
  firefox:
    container_name: firefox
    image: jlesage/firefox
    network_mode: "host"
    #    ports:
    #      - "5800:5800"
    volumes:
      - "/docker/appdata/firefox:/config:rw"
    restart: always
